CREATE OR REPLACE TABLE `horse-predictor-v2.horse_data_v2.RACES` (
  race_id            INT64     OPTIONS(description="Primary key from race.id"),
  race_number        INT64     OPTIONS(description="Race number in the day's sequence"),
  race_name          STRING    OPTIONS(description="Name of the race event"),
  race_date          TIMESTAMP OPTIONS(description="Scheduled start time of the race"),
  currency_code      STRING    OPTIONS(description="ISO-3 currency code for prize money"),
  currency_symbol    STRING    OPTIONS(description="Local currency symbol"),
  duration_ms        INT64     OPTIONS(description="Duration of the race in milliseconds"),
  track_distance_m   INT64     OPTIONS(description="Distance of the track in meters"),
  temperature_c      FLOAT64   OPTIONS(description="Ambient temperature in Celsius"),
  weather            STRING    OPTIONS(description="Weather description"),
  race_group         STRING    OPTIONS(description="Race group/category"),
  subtype            STRING    OPTIONS(description="Sub-type of the race"),
  category_id        INT64     OPTIONS(description="Foreign key to race.category.id"),
  category_breed     STRING    OPTIONS(description="Breed category in the race"),
  category_name      STRING    OPTIONS(description="Name of the breed category"),
  country_code       STRING    OPTIONS(description="ISO-3 code of race location country"),
  city_name          STRING    OPTIONS(description="City where race took place"),
  track_type         STRING    OPTIONS(description="Type of track surface"),
  video_url          STRING    OPTIONS(description="URL to race video, if available"),
  race_rules         STRING    OPTIONS(description="Full conditions text for the race"),
  payments           STRING    OPTIONS(description="Payment distribution string"),
  race_style         STRING    OPTIONS(description="Style or condition of the race"),
  created_date       TIMESTAMP OPTIONS(description="Timestamp when record was first created"),
  last_updated_date  TIMESTAMP OPTIONS(description="Timestamp when record was last updated")
);